### ISSUE TITLE
画像認識機能の追加

### ISSUE THREAD

**Issue by alice345** [alice345/kozumeru#10]
現在meruリポジトリにある，docomoAPIを用いた画像認識の処理を行う部分を移植

判定を行っていない画像を1日1回の頻度とかで解析してフラグを更新する

**Comment by gaoch** [comment]
とりあえず顔の有無判定完了。

文字の有無判定を実装したいが、問題が以下3点。
+ docomoAPIは文字のない画像も無理やり文字として認識してしまうので判定がむずかしい
+ 送信データファイルがmultipart/form-dataタイプのものしか使えないので、一旦画像ファイルを保存しなければならない
+ 一旦画像を保存するとなると、保存して文字があると判定された段階で文字認識→DBに保存する必要がある(わけてしまうと面倒)ので、判定に時間がかかる

判定の時点ではanalyzedとkindの値のみ変更するようなメソッドにしたい・・・ので画像をURLのまま扱えるAPIを探してみます
