### ISSUE TITLE
人の手による温かみあるdeployやめたい

### ISSUE THREAD

**Issue by alice345** [alice345/kozumeru#11]
やめたい

なんとかしたい

**Comment by kirikiriyamama** [comment]
+1

**Comment by alice345** [comment]
Travis CI使って自動deploy実現できそう
http://docs.travis-ci.com/user/deployment/heroku/

CircleCIのほうのheroku addonはまだβ版っぽい
https://devcenter.heroku.com/articles/circleci

つかheroku ,githubオプションもあるっぽいしCIツール使わなくてもよいのかもしれない...
https://devcenter.heroku.com/articles/github-integration

**Comment by alice345** [comment]
@gaoch 
githubオプション使って，masterが更新されたらherokuに自動でdeployされる設定に変更．
今はテスト書いてないのでCIオプションは有効にしてないのだけど，テスト書くようになったらCIオプションを有効にする必要アリ

これでgithubのmergeボタンを押すだけで，deployされる...はず...

![2015-04-18 20 48 12](https://cloud.githubusercontent.com/assets/5152601/7215300/419e30a8-e60c-11e4-9a35-a55af0c141b0.png)

**Comment by alice345** [comment]
自動デプロイ確認しました，便利〜
