### ISSUE TITLE
画像が解析済みかどうかを判定するためのカラムを追加

### ISSUE THREAD

**Issue by alice345** [alice345/kozumeru#13]
@gaoch 画像解析周りのことで相談ですー

以前から話してましたけども，今のままだとPictureモデルにはidと画像のURLしかないのでこれに画像が解析済みかどうか，その画像の種類が何かを判断するためのカラムを追加したいなーと考えています

僕の考えを以下に示します

- 解析済みかどうかを判断するために，`analyzed`カラムを追加.0は未解析(がおが追加する画像解析のスクリプトを適応させる必要がある)．1は解析済みであるため，解析しなくてもよいもの．
- 解析済みのもののうち「お給仕予定画像」「メイドさんの写っている画像」「その他」を表現するために`type`カラムを追加．0は「お給仕予定画像」，1は「メイドさんの写っている画像」，2は「その他」を表す

つまりinteger型のカラムを2つ追加するのがよいかなーと今のところ考えています．
がお的にはDB側でどういった表現にするのが一番扱いやすくなりそうですか？

**Comment by gaoch** [comment]
やまま師匠の意見をとりいれると、その分け方で賛成です。扱うデータが分けられていて良いと思います。

あと、今ふと気になったのですが、integer型で0,1のみ使うカラムは、boolean型を使ったほうがいいのでは？と思いました。

**Comment by kirikiriyamama** [comment]
> あと、今ふと気になったのですが、integer型で0,1のみ使うカラムは、boolean型を使ったほうがいいのでは？と思いました。

:sparkles:

**Comment by kirikiriyamama** [comment]
ヒント: enum

**Comment by kirikiriyamama** [comment]
`type` は Rails で予約されています…！（詳しくは STI とかでぐぐるといいよ）
代替案としては、ちょっとかっこ悪いけど kind とかかなあ。

**Comment by alice345** [comment]
@gaoch 
> あと、今ふと気になったのですが、integer型で0,1のみ使うカラムは、boolean型を使ったほうがいいのでは？と思いました。

そっちのほうがよさそう。#12 のほうもそれで統一しようか

@kirikiriyamama 
enum、便利そう～～
今回の場合でいうと

```
class Picture < ActiveRecord::Base
  enum kind: {serving: 0, maid: 1, other: 2}
end
```

てなかんじで使えるのですね。
@gaoch お給仕って単語、シュッと`serving`ってやってしまったけど何が一番よいかちょっとわからない…代替え案とかあります？他の部分でも使いそうな単語なので慎重に決めたい
