### ISSUE TITLE
お給仕予定日を表現するモデルを作成

### ISSUE THREAD

**Issue by alice345** [alice345/kozumeru#16]
## やりたいこと
- お給仕をするメイドさんとそのメイドさんのお給仕する日を紐付けたい
- そのために解析した画像から得られたお給仕の予定日を保存したい
- 最終的には直感的に「◯日の△階は推しのメイドさんが多い」ということが分かる情報を提供したい
- 表示的にはカレンダー形式がよさそう？

## 問題
- お給仕予定日に関するモデルの部分をどういった構造にするのがいいかわからない

**Comment by alice345** [comment]
@kitak さんに相談させてもらいました．それも踏まえて

- メイドさんのお給仕情報に関するモデル，`Serving`モデルを作成する
- `Serving`モデルは，お給仕予定日の画像から読み取った日付(ex.2015年5月1日)を表現するためのモデル
- メイドさんの情報を扱う`Maid`モデルとは1対1の関係
- その文字が書かれていた画像の`Picture`モデルとも1対1の関係
- 具体的には
  - integer: maid_id
  - integer: picture_id
  - datetime: 認識した日付
  - integer: location(0: 4階，1: 6階, 2: 7階, 3: ドンキ店)
  - string: miss_analyzed(認識に失敗して，dateオブジェクトに変換できなかった文字列.ex 2015年13月1o日．)

`Maid`のテーブルに`floor`があるのに`location`を追加がある理由は，所属する階とその日にお給仕する階は別のもモノであるため．プレミアムや新人メイドさんは様々な階でお給仕を行うし，イベントによっては所属する階と違うところでお給仕することもある．

また認識に失敗した文字列も保存する理由としては，失敗した文字列は人間の手で修正して正しく`date`オブジェクトに変換させたいという目的のため．

最初は日付を扱うだけかと思っていましたが，「お給仕」を表現するには日付だけでは難しいとなりこういった形にしました

@gaoch 昼間に相談したようにこんなかんじでいこうとおもいます．もし抜けてるところ，変更したほうがいいなーと思う部分があったらツッコミお願いします！

**Comment by alice345** [comment]
まずは僕のほうで保存するためのモデルの作成，migrationファイルの作成のほうをやろうと思います
で，実際にDBに保存するときの処理は @gaoch のほうでやってもらえればいいなと！(別issueに切り分けますね)

**Comment by kitak** [comment]
Servingモデルについて

> メイドさんの情報を扱うMaidモデルとは1対1の関係

ここって1対多かな、と思いました。
ひとりのメイドさんって、例えば4月3日と4月4日の複数の日付に給仕するよね

**Comment by alice345** [comment]
@kitak ハッ！確かにそうですね，間違えてました...!ご指摘ありがとうございます！

**Comment by alice345** [comment]
@gaoch 画像から読み取れるお給仕日って`datetime`(日時),`date`(日付),`tme`(時間)のこの3つのうちでれでしたっけ...？

**Comment by gaoch** [comment]
今はdateにしてます！できればdatetimeにしてプレミアム対応にしたいけども・・・

**Comment by alice345** [comment]
@gaoch なるほど！でもプレミアム対応にすると普通のメイドさんは`time`のほうわかんないんすよね…

`date`と`time`のカラムを別々に分けて，プレミアムの人だけ`time`カラムに情報を入れるっていう形ならなんとかなるかな

**Comment by gaoch** [comment]
普通のメイドさんは00:00:00にしようと思ってたけど、確かに分けたほうが良さそう！
そしてプレミアムのtime対応にすると、お給仕開始時間、お給仕終了時間のカラムが必要になるね
まあでもそれはのちのち・・・

**Comment by alice345** [comment]
あっお給仕開始時間とお給仕終了時間になるのか！！！
後々必要になると思うのでカラムだけ作っておいて，利用シーンはまたあとで考えましょう
