### ISSUE TITLE
CircleCI導入

### ISSUE THREAD

**Issue by alice345** [alice345/kozumeru#31]
やっとテストを書いたので(といっても本当に少しだけど...) ，CIツールを導入したい．毎回`rake rspec`叩くの面倒すぎる

**Comment by kirikiriyamama** [comment]
:sparkles:

**Comment by alice345** [comment]
はじめてのCircleCI記念スクショ

![2015-04-27 01 30 06](https://cloud.githubusercontent.com/assets/5152601/7338132/09a7e50a-ec7d-11e4-9431-f7edd31942d3.png)

**Comment by alice345** [comment]
herokuもほうもCI連携しました

![2015-04-27 01 33 19](https://cloud.githubusercontent.com/assets/5152601/7338206/e49eeabc-ec7f-11e4-9f36-b1bc07743039.png)

**Comment by alice345** [comment]
![image](https://cloud.githubusercontent.com/assets/5152601/7338258/5b44a160-ec81-11e4-811a-95a19584bc6c.png)
