### ISSUE TITLE
ツイートの取得方法

### ISSUE THREAD

**Issue by alice345** [alice345/kozumeru#5]
## これまでの案
`Twitter::Streaming::Client`を使ってメイドさんのツイートをリアルタイムに取得，解析を考えていた

## でもなんか...
めんどくさそう…`Twitter::Streaming::Client`の`#site`メソッドがそれっぽかったけども，これを使うには申請が必要な模様(一応申請はした)

![2015-04-05 21 38 57](https://cloud.githubusercontent.com/assets/5152601/6996856/2e876ee6-dbdd-11e4-9cd2-910129af5603.png)
https://dev.twitter.com/streaming/sitestreams#Applying_for_access
ぽちさん情報ありがとうございました！

## そこに現れた救世主(？)やまま師範
![2015-04-05 20 25 02](https://cloud.githubusercontent.com/assets/5152601/6996869/972d5226-dbdd-11e4-8391-2d8e02186f2a.png)

たしかにリアルタイムじゃなくても1時間に1回とか取ってくればよさそう(200ツイートもしないでしょう，たぶん…)具体的には`#user_timeline`のオプションである`since_id`に保存してある中で最新のツイートを指定してやれば全部のツイートを追えそうな気がする

**Comment by kirikiriyamama** [comment]
出勤情報
