### ISSUE TITLE
メイドさんの卒業に対応

### ISSUE THREAD

**Issue by alice345** [alice345/kozumeru#7]
> 結論から言うと、卒業フラグは別のカラム（e.g. graduated）のほうがよいと思います。なぜならば、卒業しているか否かと所属階は別のデータだから。unix 哲学のひとつ "各プログラムが一つのことをうまくやるようにせよ" の考え方です。
それと、ユニーク制約はかけないほうがいいと思いました。メイドさんの名前を一意にしてうれしいことがない、言い換えると一意にする意味がないと思ったからです。また、技術的にも難しくて、まず、DB の制約（ユニークインデックス）では単純に対象のカラムの一意性を保つことしか出来ません。つまり、論理削除に対応出来ません。Rails の validation は論理削除に対応出来ますが、若干わかりづらくなるし、そこまでのコストをかけて一意に保つ必要はないと考えました。

**Comment by alice345** [comment]
> あと、人間がつらい思いしてまで integer にする必要はないです。カリカリにチューニングしなきゃいけないアプリも世の中にはあるけど、少なくとも kozumeru はそうではないと思います。どういうデータを表現したいか、を第一に考えましょう。実装は二の次でです。実装はあとからどうとでも出来るけど、DB は（運用にはいってしまうと）難しいです。
メイドさん事情よくわかっていないから判断出来ないんだけど、所属階にドンキ？とかあるんだよね？ドンキで複数フロアはありえる？あと、今後他の店舗が出来る可能性、その店舗が複数フロアである可能性はどうかな？

**Comment by alice345** [comment]
> 全然関係ないんだけど、PR は小さくするとよいと思いました。少なくとも、PR のタイトルと関係ないコミットは（多少であればいいけど）別 PR にしましょう。レビューする人が大変だし、コンフリクトするし、ともかく出来たところから master にいれたほうがよいです。unix 哲学の "小さいものは美しい" です。

**Comment by alice345** [comment]
@kirikiriyamama 「各プログラムが一つのことをうまくやるようにせよ」ですか、なるほど

卒業のフラグには0 or 1の`graduated`カラムを追加して対応しようと思います

> メイドさん事情よくわかっていないから判断出来ないんだけど、所属階にドンキ？とかあるんだよね？

はい、あります。メイドさんの所属は「プレミアム」「本店4階」「本店6階」「本店7階」「新人」という風になっています。


> ドンキで複数フロアはありえる？あと、今後他の店舗が出来る可能性、その店舗が複数フロアである可能性はどうかな？

現段階ではドンキに複数フロアはありませんが、本店のように複数フロアになる可能性は0ではないと思います。同様に他の店舗ができることもありえますし、またその店舗が複数フロアであることもありえると思います(ex ドンキ3階、ドンキ4階、渋谷店5階、渋谷店6階


> どういうデータを表現したいか、を第一に考えましょう

このことなのですが今回の例で言うと

「所属のステータスを全て数値で表現しようとすると、「6階」「プレミアム」といった本来表したい状態から剥離してしまう。あくまで数値のフラグで表現したいのは「卒業した」「卒業していない」といった状態だけであるから、ステータスで一括りにするのではなく表現したいデータ毎に分割する(この場合はカラム)ほうがよい」

という認識をしました(もしそれ勘違いやでってのがあったらマサカリください…)

**Comment by alice345** [comment]
`maids`テーブルに`graduated`カラムを作成
0のときは卒業していない．つまり現役のメイドさん．
1のときは卒業して現在はいないメイドさんを示す．

クローラーの部分で更新するかどうかを検知すべきだがその部分は未実装．
まずは確実に必要になるであろうカラムのほうを追加する

**Comment by kirikiriyamama** [comment]
boolean でいんじゃないすか？

**Comment by kirikiriyamama** [comment]
あとでちゃんとコメントするね
